version: '3.8'

services:
  webauthn-demo:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - webauthn-data:/data
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  webauthn-data: 